# Generated by Django 5.1.3 on 2024-12-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
