# Generated by Django 5.1.3 on 2024-12-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0002_alter_category_options_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
