# Generated by Django 5.1.3 on 2024-12-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0003_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.DateField(null=True),
        ),
    ]
