# Generated by Django 5.1.3 on 2024-12-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0004_alter_user_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
