# Generated by Django 5.1.3 on 2024-12-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0005_alter_user_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
