# Generated by Django 5.1.3 on 2024-12-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0006_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
