# Generated by Django 5.1.3 on 2024-12-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0007_alter_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
