# Generated by Django 5.1.3 on 2024-12-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0008_rename_is_sale_product_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
