# Generated by Django 5.1.3 on 2024-12-25 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0009_remove_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_precentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
