# Generated by Django 5.1.3 on 2024-12-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0010_product_sale_precentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_precentage',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
